In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2080 SUPER'

We'll learn how to manipulate tensors using Pytorch tensor library.
- how the data is stored in memory
- how certain operations can be performed on large tensors 
- numpy interoperability
- gpu acceleration

# Tensors

In [3]:
a = [1.0, 2.3, 4.5]

In [4]:
a = torch.ones(3) # one-dim tensor size 3 filled with 1
a

tensor([1., 1., 1.])

In [5]:
a[0]

tensor(1.)

In [6]:
float(a[0])

1.0

Python objects are stored in memory, tensors in pytorch are stored in unboxed C numeric types.

In [7]:
# lets create coordinates of a triangle 2D
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
# or passing as coordinates
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
# shape of the tensor
points.shape

torch.Size([3, 2])

In [13]:
# initialize a tensor with specific dimensions
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Indexing tensors

In [22]:
some_list = list(range(10))
some_list[1:4:2]

[1, 3]

In [21]:
some_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
points[0:3:2]

tensor([[0., 0.],
        [0., 0.]])

Pytorch also have an advanced indexing, used as a powerful feature between others developers. 

## Named tensors 

The dimensions (or axes) of our tensor usually index something like pixel locations or color channels. This means when we want to index into a tensor, we need to remember the ordering of the dimensions and write our indexing accordingly.



In [29]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.78, 0.0722])

In [30]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [31]:
batch_t

tensor([[[[ 0.7819,  0.5808, -1.0045,  0.9410,  1.9312],
          [-0.8312, -1.2887,  0.1066,  0.5999,  0.1806],
          [-1.6966, -0.6013,  0.9279, -1.2569,  0.9823],
          [ 1.6346,  0.0363,  2.1404,  0.8002, -0.1722],
          [-1.2858,  0.2372,  1.1009, -0.4881,  0.4264]],

         [[-1.6378, -0.8108,  1.0617, -1.4675, -0.7600],
          [-1.6526, -1.0222, -1.3802,  0.4912,  1.3696],
          [ 1.0801,  0.7982,  0.2925, -0.0907,  0.1693],
          [ 0.5236, -0.2257, -0.8769, -1.3331,  0.3376],
          [-0.0588,  0.8637, -0.4297, -0.9982,  0.5919]],

         [[-0.4046, -0.4428, -0.2595,  0.0892,  0.2636],
          [-0.7281,  0.4554,  0.6661, -1.5187, -0.7507],
          [ 1.2599, -2.6768, -0.3505, -0.7093,  2.1740],
          [-1.4718, -1.3350, -0.4883,  2.2749,  0.8795],
          [ 0.4287, -0.4178,  0.5689,  0.6871, -0.0300]]],


        [[[-0.2983,  2.7361,  1.7560, -0.8485, -0.2876],
          [ 0.6648,  0.2645, -0.0536,  0.1974, -0.2033],
          [-1.6270, -0.

Pytorch 1.3 introduced a named tensors. **Tensor factory** functions such as **tensors** and **rand** take a names argument.


In [32]:
Weights_named = torch.tensor([0.2125, 0.755, 0.0345], names=["channels"])
Weights_named

/tmp/ipykernel_8638/1321878458.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1408.)
  Weights_named = torch.tensor([0.2125, 0.755, 0.0345], names=["channels"])


tensor([0.2125, 0.7550, 0.0345], names=('channels',))

In [35]:
img_named = img_t.refine_names(..., "channels", "rows", "columns")
img_named

tensor([[[ 0.9455,  0.9939,  0.4753, -0.3491,  1.0914],
         [-0.2602,  1.3988, -1.7387, -0.0784, -0.2512],
         [ 2.4587,  1.1470, -0.2353, -0.3455, -1.0662],
         [-0.1570, -1.5262, -0.6244,  0.8368,  0.9062],
         [-1.5603,  0.4683,  0.4650,  1.8803,  0.0094]],

        [[ 0.3564,  0.4882,  0.5638, -0.8486, -1.0810],
         [-0.5640,  0.2530,  0.0352,  0.9452,  0.0673],
         [-0.2041,  0.4780, -0.7393,  1.4690, -0.2960],
         [ 0.1271, -1.2029, -2.4153, -1.2643,  0.7097],
         [ 0.7378,  0.6264,  1.3681, -0.3487, -1.2724]],

        [[-0.4709, -0.4903,  2.9442,  0.6665, -0.6970],
         [-1.3665,  0.3001, -1.3248,  0.7635,  0.0216],
         [ 0.4380,  2.7411,  0.0673, -1.5146,  0.0333],
         [-1.6363,  0.3584, -0.8034, -2.2320,  0.2563],
         [ 0.1360, -1.2189,  1.0704,  0.6455,  1.5432]]],
       names=('channels', 'rows', 'columns'))

Named tensors have the potential to eliminate many sources of alignment errors which can be a source of headaches.

### Tensor element types

What kinds of numeric types we can store in a Tensor? Python numeric types can be suboptimal for several reasons:

- Numbers in python are objects: stored with a boxing operation
- Lists in python are meant for sequential collections of objects
- Python interpreter is slow compared to optimized, compiled code

In [37]:
# torch dtypes
torch.float
torch.float32
torch.float64
torch.half
torch.int


torch.int32

In [38]:
torch.uint8

torch.uint8