In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2080 SUPER'

We'll learn how to manipulate tensors using Pytorch tensor library.
- how the data is stored in memory
- how certain operations can be performed on large tensors 
- numpy interoperability
- gpu acceleration

# Tensors

In [4]:
a = [1.0, 2.3, 4.5]

In [5]:
a = torch.ones(3) # one-dim tensor size 3 filled with 1
a

tensor([1., 1., 1.])

In [6]:
a[0]

tensor(1.)

In [7]:
float(a[0])

1.0

Python objects are stored in memory, tensors in pytorch are stored in unboxed C numeric types.

In [8]:
# lets create coordinates of a triangle 2D
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
# or passing as coordinates
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
# shape of the tensor
points.shape

torch.Size([3, 2])

In [11]:
# initialize a tensor with specific dimensions
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Indexing tensors

In [12]:
some_list = list(range(10))
some_list[1:4:2]

[1, 3]

In [21]:
some_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
points[0:3:2]

tensor([[0., 0.],
        [0., 0.]])

Pytorch also have an advanced indexing, used as a powerful feature between others developers. 

## Named tensors 

The dimensions (or axes) of our tensor usually index something like pixel locations or color channels. This means when we want to index into a tensor, we need to remember the ordering of the dimensions and write our indexing accordingly.



In [13]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.78, 0.0722])

In [17]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [18]:
batch_t

tensor([[[[-7.0865e-01,  9.7672e-01, -6.3954e-01,  1.5766e-01,  1.1037e+00],
          [ 1.5463e+00,  1.2739e-01, -7.4799e-01, -2.6169e-01, -1.0695e+00],
          [ 4.0478e-01, -1.1229e+00,  1.1241e+00, -5.7383e-01, -7.2641e-01],
          [-7.1018e-02, -2.8328e-01, -9.0021e-01,  9.9194e-01, -1.3993e+00],
          [ 2.0287e+00, -7.1575e-01,  4.9782e-01,  1.5286e+00, -1.7222e+00]],

         [[ 1.3631e+00, -1.0093e+00,  5.0792e-01, -1.3808e+00, -8.2902e-01],
          [ 2.2875e-01, -7.7122e-01,  1.2225e+00,  1.7267e+00,  1.4250e+00],
          [ 1.7175e+00, -9.4228e-01,  4.8240e-01, -1.9607e+00,  2.3667e-01],
          [ 1.5387e-01, -6.2021e-01, -4.6766e-01, -2.6442e-01,  4.2527e-01],
          [ 1.3664e-01, -1.9370e+00,  2.8235e-01, -4.5833e-02,  4.6699e-01]],

         [[ 6.7786e-01, -9.8803e-03,  4.3896e-02, -1.4911e+00, -1.2718e+00],
          [-1.7003e+00,  9.7886e-01, -7.2707e-01,  3.1534e-01, -7.2268e-01],
          [-6.8551e-01,  1.5914e-01, -3.2088e-01,  6.1872e-01, -2.9760e-

Pytorch 1.3 introduced a named tensors. **Tensor factory** functions such as **tensors** and **rand** take a names argument.


In [30]:
img_t.mean(-3)

tensor([[ 0.0857, -0.3917,  0.3448,  0.4952,  0.3418],
        [ 0.4057,  1.0863,  0.9266, -0.0197,  0.2515],
        [-0.4586,  0.5306, -0.0468,  0.5962,  1.0785],
        [ 0.0461,  0.9818,  0.7190, -1.1122, -0.5134],
        [-0.3320, -0.4755,  0.3437, -0.4042,  0.1216]])

In [21]:
img_t.size()

torch.Size([3, 5, 5])

## Named tensors

As data is transformed through multiple tensors, keeping track of which dimension contains what data can be error-prone.

In [38]:
# imagine a 3D image, 3D tensor, and we want to convert it to grayscale.
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [39]:
# we also want to generalize, from a 2D grayscale, add a third dim to add color.
# adding a batch_t.
batch_t = torch.randn(2, 3, 5, 5)

In [40]:
# so RGB channels are always on dimension -3.
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [42]:
# another step of the process
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

...This is a too complicated and error prune process. For that we use named tensors.

In [43]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [45]:
# to add names to a existing tensor, use .refine_names()
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
img_named

tensor([[[ 0.0947, -0.7375, -0.3886,  0.2595, -1.6724],
         [-1.2216, -0.1523, -1.3980, -0.2321,  1.0383],
         [-0.8778, -0.1185, -1.0319,  0.3926,  0.2442],
         [-1.3668, -1.7488,  0.6225,  0.4324, -0.0553],
         [-0.5542, -2.6776,  0.6894,  1.6461, -0.7349]],

        [[-0.5235, -2.0107, -0.2135, -3.2689, -2.4123],
         [-1.9856, -1.1923, -0.4498,  0.5827, -0.1437],
         [ 0.1517, -0.1497, -0.2720, -2.4248,  0.4925],
         [-1.2434,  2.8643,  1.6844,  0.1003, -0.3706],
         [-0.5419, -1.7610, -2.4077,  0.0674,  0.0040]],

        [[ 0.0806, -0.1083, -1.0673, -1.0480, -0.1287],
         [ 0.1852, -2.0077,  0.9057, -1.4238, -1.2967],
         [-1.3148, -0.9351, -0.6671,  0.1097,  1.7359],
         [-1.6605,  1.8171,  0.9547,  0.3827,  0.1359],
         [ 0.6059, -0.6129, -0.6666, -0.5589, -1.5323]]],
       names=('channels', 'rows', 'columns'))

In [46]:
batch_named

tensor([[[[-0.1649, -1.2870, -1.1137,  0.3297,  0.7800],
          [-1.5436, -0.7299,  2.3760, -0.8542,  1.2475],
          [ 1.0200, -2.3685, -2.0618, -0.5795,  1.3302],
          [ 0.1735, -1.4492, -1.1893,  1.3111,  1.7122],
          [ 0.7962,  0.7818,  0.7990,  0.7661,  0.8400]],

         [[ 0.5923,  0.5611, -0.6370, -0.6348,  0.6865],
          [-1.8531,  1.5370, -0.8730, -0.3203, -0.9351],
          [ 1.3536, -1.1781, -0.5665, -0.2706, -0.1327],
          [-0.3308,  1.4281, -0.8178, -0.0404,  1.7440],
          [ 2.1795,  0.1132, -1.3456, -0.4383, -0.0717]],

         [[ 0.3562,  0.4753, -1.4866,  0.3955,  1.7102],
          [ 0.4515,  1.6538,  1.2416, -0.4988, -0.0052],
          [-0.6367, -1.6565, -1.3755, -0.7261,  1.5513],
          [ 0.2134,  0.2365,  0.7124, -1.8809,  0.3725],
          [-0.1931, -1.6686,  0.1771, -0.2743, -0.2706]]],


        [[[-0.0385, -0.1041, -0.1724,  1.4859, -1.5508],
          [-0.2985, -0.1178, -0.8857, -0.6669, -0.3411],
          [-0.2994,  0.

Pytorch will now check the names for us on two inputs operations. So far, it does not automatically align dimensions, so we need to do this explicitly. The method align_as returns a tensor with missing dimensions added and existing ones permuted to the right order

In [47]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]], names=('channels', 'rows', 'columns'))

In [48]:
# some operations also take named dimensions as input
(img_named * weights_aligned).sum('channels')

tensor([[-0.3485, -1.6026, -0.3124, -2.3584, -2.0901],
        [-1.6665, -1.0300, -0.5535,  0.2646,  0.0243],
        [-0.1730, -0.1998, -0.4621, -1.6429,  0.5295],
        [-1.2997,  1.8080,  1.4059,  0.1913, -0.2670],
        [-0.4617, -1.8730, -1.6235,  0.3578, -0.2640]],
       names=('rows', 'columns'))

# Tensor Element types

Python numerical types are suboptimal, and for that data science libraries rely on numpy or others dedicated data structures to improve efficience.

## Numeric types

- torch.float32
- torch.float64 or touch.double
- torch.int8
- torch.bool
- ...

As we'll see, computations happening in nns are typically executed with 32-bit floating-point precision. 64-bits will not improve performance.

16-bit precision can be used on some cpus and gpus.

## Managing a tensor's dtype attribute

In [50]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [51]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [53]:
# we can also casting the result of some operations on tensors
torch.zeros(10, 2).double()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [54]:
# or using to method
torch.zeros(19, 2).to(torch.short)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

When mixing input types in operations, the inputs are converted to the larger type automatically.

# The tensor API

Some basic examples

In [56]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Tensors: Scenic views of storage

- Low level understanding of how the tensors works

Values in tensors are allocated in contiguous chunks of memory managed by `torch.Storage` instances.

A storage is a one-dimensional array of numerical data: that is, a contiguous block of memory containing numbers of a given type
