# TensorFlow stack

- tensors
- tensors operations
- backpropagation
- layers
- loss function: defines the feedback signal
- optimizer
- metrics: to evaluate model performance, such as accuracy
- training loop

# Constant tensors and variables

## all ones or all zeros tensors

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones(shape=(2, 1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
y = tf.zeros(shape=(2, 1))
print(y)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


## random tensors

In [4]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.) # random values from a normal distribution
print(x)

tf.Tensor(
[[-1.0845584 ]
 [ 0.37289742]
 [ 0.6119003 ]], shape=(3, 1), dtype=float32)


In [6]:
y = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.) # random values from a uniform distribution btw 0 and 1
print(y)

tf.Tensor(
[[0.52079487]
 [0.83852303]
 [0.35648775]], shape=(3, 1), dtype=float32)


In [7]:
# tensors not support assignment
x = tf.ones(shape=(2, 2))
x[0, 0] = 0

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

We have a specific class that handles objects that need to be updated during to process `tf.Variable`

## creating a variable

In [8]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.24559118],
       [0.175641  ],
       [0.04454513]], dtype=float32)>


In [9]:
v.assign(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [10]:
# works for a subset
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [12]:
# assign_add and assign_sub are efficient equivalents of += and -=:
v.assign_add(tf.ones((3, 1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

## tensor operations: doing math in tensorflow

In [13]:
a = tf.ones((2, 2))
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b) # product of two tensors
e *= d # element-wise

In [14]:
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

## gradient tape api