In [1]:
import torch

In [2]:
t = torch.tensor(
    [[1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3]],
    dtype=torch.int32
)

In [3]:
t.size()

torch.Size([3, 4])

In [4]:
t.shape

torch.Size([3, 4])

In [5]:
len(t.shape) # rank

2

In [6]:
t

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)

In [7]:
torch.tensor(t.shape).prod()

tensor(12)

In [8]:
t.numel() # number of elements of the tensor

12

In [9]:
t.reshape(1, 12)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]], dtype=torch.int32)

In [10]:
t.reshape(2, 6)

tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]], dtype=torch.int32)

In [11]:
t.reshape(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)

In [12]:
t.reshape(4, 3)

tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]], dtype=torch.int32)

In [13]:
t.reshape(12, 1)

tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]], dtype=torch.int32)

In [14]:
t.reshape(6, 2)

tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]], dtype=torch.int32)

All these values are factor of 12

In [15]:
t.reshape(2, 2, 3)

tensor([[[1, 1, 1],
         [1, 2, 2]],

        [[2, 2, 3],
         [3, 3, 3]]], dtype=torch.int32)

In [16]:
# squeeze
print(t.reshape(1, 12))
print(t.reshape(1, 12).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]], dtype=torch.int32)
torch.Size([1, 12])


In [17]:
print(t.reshape(1, 12).squeeze())
print(t.reshape(1, 12).squeeze().shape)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=torch.int32)
torch.Size([12])


Squeeze the tensor remove all axis of 1. Unsqueeze the tensor does the contrary!

In [21]:
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0))
print(t.reshape(1, 12).squeeze().unsqueeze(dim=0).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]], dtype=torch.int32)
torch.Size([1, 12])


In [32]:
print(t.reshape(2, 6, 1).squeeze().unsqueeze(dim=1).shape)

torch.Size([2, 1, 6])


Unsqueeze will create a dimension of 1 in some rank of the tensor.

In [36]:
# flatten works like squeeze on [1, -1]
t.flatten()

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=torch.int32)

In [41]:
t1 = torch.tensor([[1, 2, 3], [2, 2, 2]])
t2 = torch.tensor([[1, 2, 1], [1, 1, 1]])
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 3])

In [42]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 6])

In [43]:
t1.shape

torch.Size([2, 3])

## CNN Flatten Operation Visualized - Tensor Batch Processing for Deep Learning

In [48]:
t1 = torch.tensor(
    [[1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]]
)
t2 = torch.tensor(
    [[2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2],
    [2, 2, 2, 2]]
)
t3 = torch.tensor(
    [[3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3],
    [3, 3, 3, 3]]
)

In [52]:
# it's like [B, H, W] dimensions
# to be on the correct shape for pytorch we need
torch.stack((t1, t2, t3)).shape

torch.Size([3, 4, 4])

In [57]:
# now we have:
# 3 images
# 4 by 4 (H x W)
# grayscale, because the C = 1
t_stack = torch.stack((t1, t2, t3)).unsqueeze(dim=1)

In [58]:
# with all tensors stacked, we want to flatten each w x h tensor
# because are in fact the data (the pixels)
t_stack.flatten(start_dim=1).shape

torch.Size([3, 16])

In [59]:
t_stack.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [64]:
t_stack.reshape((t_stack.shape[0], -1))

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])