# Checking derivative as an limit iteration

In [1]:
def f(x):
    return 3 * x ** 2 - 4 * x

In [2]:
def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

In [5]:
h = 0.1
for i in range(6):
    numerical_lim_value = numerical_lim(f, 1, h)
    print("h={}, numerical limit={}".format(round(h, 6), round(numerical_lim_value, 6)))
    h *= 0.1

h=0.1, numerical limit=2.3
h=0.01, numerical limit=2.03
h=0.001, numerical limit=2.003
h=0.0001, numerical limit=2.0003
h=1e-05, numerical limit=2.00003
h=1e-06, numerical limit=2.000003


# Gradient with Torch 

In [15]:
import torch

x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

`requires_grad` keep history for you, and make possible to you calculate derivatives of this variable.

In [16]:
print(x.grad)

None


In [17]:
y = torch.dot(x, x)
print(y)

tensor(14., grad_fn=<DotBackward0>)


In [18]:
z = y + 10

In [19]:
z.backward()

In [20]:
x.grad

tensor([0., 2., 4., 6.])

In [21]:
y.grad

/home/luba/.pyenv/versions/3.9.0/lib/python3.9/site-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


In [12]:
x.zero_

<function Tensor.zero_>

In [14]:
x.grad

tensor([0., 2., 4., 6.])

In [26]:
# another example
x.grad.zero_()
y = x.sum()
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


In [42]:
# x.grad.zero_()
x = torch.arange(3., requires_grad=True)
y = x * x
y.backward(torch.tensor([1., 1., 0]))
print(x.grad)

tensor([0., 2., 0.])


In [38]:
y

tensor([0., 1., 4.], grad_fn=<MulBackward0>)

In [43]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**3 - b**2

In [45]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
print(a.grad, b.grad)

tensor([36., 81.]) tensor([-12.,  -8.])
