# Tensors Attributes

In [1]:
import numpy as np

In [8]:
 x = np.array([[[5, 15],
               [6, 5]],
               [[56, 56],
               [56, 55]],
              [[5, 32],
              [3, 4]]])


In [9]:
x.ndim

3

In [10]:
x.shape

(3, 2, 2)

In [11]:
x.dtype

dtype('int64')

In [12]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Manipulating tensors in numpy

In [15]:
my_slice = train_images[10: 100]
my_slice.shape

(90, 28, 28)

In [17]:
train_images.shape

(60000, 28, 28)

In [18]:
# more detailed slicing
same_slice = train_images[10: 100, :, :]
same_slice.shape

(90, 28, 28)

In [20]:
train_images[:, 7: -7, 7: -7].shape

(60000, 14, 14)

# The notion of data batches

Deep learning models don't process an entire dataset at once; rather, they break the data into **small batches**. 

# Element-wise operations

Element-wise operations = operations that are applied independetly to each entry in the tensors being considered.

In [23]:
# naive relu
# x is a rank-2 numpy array
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [26]:
x = np.array([[1, 2, 3],
    [2, -5, 6]])

In [28]:
naive_relu(x)

array([[1, 2, 3],
       [2, 0, 6]])

We normally use numpy to do ours operations, because it is very well optimized.

In [38]:
x = np.random.random((32, 10))
y = np.random.random((10,))
# expand dims of y
y = np.expand_dims(y, axis=0)
# repeat 32 times to broadcast
y = np.concatenate([y] * 32, axis=0)

In [41]:
y.shape

(32, 10)

# Tensor reshaping

In [43]:
train_images_reshaped = train_images.reshape((60000, 28 * 28))

In [44]:
train_images.shape

(60000, 28, 28)

In [45]:
train_images_reshaped.shape

(60000, 784)

In [50]:
x = np.array([[0., 1],
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [47]:
x = x.reshape((6, 1))

In [48]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [53]:
x.reshape((2, 3))

array([[0., 1., 2.],
       [3., 4., 5.]])

In [54]:
x.transpose()

array([[0., 2., 4.],
       [1., 3., 5.]])

In [55]:
x

array([[0., 1.],
       [2., 3.],
       [4., 5.]])